config/routes.rb
Rails.application.routes.draw do
  resources :user_tasks

  root 'user_tasks#index'

end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
	validates :description, :due, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]

  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = UserTask.new(user_task_params)

   respond_to do |format|
     if @user_task.save
       format.html { redirect_to @user_task }
       format.js {}
       format.json { render :show, status: :created, user_task: @user_task }
     else
       format.html { render :new }
       format.js { render :action => "new"}
       format.json { render json: @user_task.errors, status: :unprocessable_entity }
     end
   end

  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    respond_to do |format|
      if @user_task.update(user_task_params)
        format.html { redirect_to @user_task }
        format.js {}
        format.json { render :show, status: :ok, location: @user_task }
      else
        format.html { render :edit }
        format.js { render :action => "edit"}
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
   @user_task.destroy
   respond_to do |format|
     format.html { redirect_to user_tasks_url }
     format.js {}
     format.json { head :no_content }
   end
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = UserTask.find(params[:id])
    end

    def all_tasks
      @user_tasks = UserTask.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>TaskList</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/cosmo/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "User Tasks", user_tasks_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/user_tasks/_form.html.erb
<%= form_for(@user_task) do |f| %>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/index.html.erb
<h1>Tasks</h1>

<p><%= link_to 'New User task', new_user_task_path, remote: true %></p>

<div id="task-form"></div>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_tasks.each do |user_task| %>
      <tr>
        <td><%= user_task.description %></td>
        <td><%= user_task.due %></td>
        <td><%= link_to 'Show', user_task %></td>
        <td><%= link_to 'Edit', edit_user_task_path(user_task) %></td>
        <td><%= link_to 'Destroy', user_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/user_tasks/new.html.erb
<h1>New User Task</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>